# Generated by Django 4.1.2 on 2022-10-20 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_pizza_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['title'], 'verbose_name': 'Pizza', 'verbose_name_plural': 'Pizzas'},
        ),
    ]
