# Generated by Django 4.1.2 on 2022-10-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_box_pizzaroll_pizzaslice_toping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='pizzaroll',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='pizzaslice',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='toping',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Price'),
        ),
    ]
